Feature/daniel contreras semantic exercise
danielContrerasL/html-tutorial pull request #1
Opened 2020-04-22 17:04 UTC by danielContrerasL

This is my web page  and the implementation of correct semantics tags

2020-04-22 20:21 UTC, juancho11gm commented on 1-the-basics/index.html
> +</html>
Good job, remember to create a new branch for each exercise. Only for today let's keep the basic HTML exercise and semantic exercise in the same Pull Request.

2020-04-22 20:31 UTC, juancho11gm requested changes
Look at the layout of the exercise here: https://github.com/pushdev-code/html-tutorial/blob/master/3-semantic-html/index.md.  I see that you are nesting all the tags inside the `<main>`
Please use the tags that we are asking for the basic structure. Inside that elements you can put the content that you want. Something like this:
```
<body>
    <header>
        <nav>
            <!-- your content -->
        </nav>
    </header>
    <main>
        <!-- here you have to include the <article> tag as it's in the tree (DOM) image -->
    </main>
    <aside>
        <!-- your content -->
    </aside>
    <footer>
        <nav>
            <!-- your content -->
        </nav>
    </footer>
</body>
```

2020-04-22 21:05 UTC, juancho11gm commented on 1-the-basics/index.html
> +</html>
Using <br> it's a bad practice because it's not a semantic tag. We are going to see how to put a line break with CSS.

2020-04-26 00:37 UTC, danielContrerasL commented
> Look at the layout of the exercise here: https://github.com/pushdev-code/html-tutorial/blob/master/3-semantic-html/index.md. I see that you are nesting all the tags inside the `<main>`
> Please use the tags that we are asking for the basic structure. Inside that elements you can put the content that you want. Something like this:
> 
> ```
> <body>
>     <header>
>         <nav>
>             <!-- your content -->
>         </nav>
>     </header>
>     <main>
>         <!-- here you have to include the <article> tag as it's in the tree (DOM) image -->
>     </main>
>     <aside>
>         <!-- your content -->
>     </aside>
>     <footer>
>         <nav>
>             <!-- your content -->
>         </nav>
>     </footer>
> </body>
> ```



> Look at the layout of the exercise here: https://github.com/pushdev-code/html-tutorial/blob/master/3-semantic-html/index.md. I see that you are nesting all the tags inside the `<main>`
> Please use the tags that we are asking for the basic structure. Inside that elements you can put the content that you want. Something like this:
> 
> ```
> <body>
>     <header>
>         <nav>
>             <!-- your content -->
>         </nav>
>     </header>
>     <main>
>         <!-- here you have to include the <article> tag as it's in the tree (DOM) image -->
>     </main>
>     <aside>
>         <!-- your content -->
>     </aside>
>     <footer>
>         <nav>
>             <!-- your content -->
>         </nav>
>     </footer>
> </body>
> ```

ok thanks, I got confused with the exercise explanation but i will correct the error

2020-04-29 01:33 UTC, pushdev-code approved these changes

2020-04-29 03:00 UTC, merged