Feature/daniel contreras form exercise
danielContrerasL/html-tutorial pull request #2
Opened 2020-04-25 22:16 UTC by danielContrerasL

This is a form to get user information for aply to subsidy

2020-04-29 01:35 UTC, pushdev-code requested changes
I see your form exercise is completed, but please make sure you have one exercise Per PR, I see the basics and the semantics exercises in this one, so please don't include them in these set of changes.

2020-05-02 19:10 UTC, pushdev-code requested changes
Some small comments left, please move accessible exercise to its own PR.

2020-05-02 19:10 UTC, pushdev-code commented on 4-forms-validations/form.html
> +        <p>This is a form to apply for a sport subsidy</p>
this should be a <h1>

2020-05-02 19:10 UTC, pushdev-code commented on 4-forms-validations/form.html
> +                <select id="gender" required>
```suggestion
                <label for="gender">Gender: </label><select id="gender" required>
```

2020-05-02 19:10 UTC, pushdev-code commented on 4-forms-validations/form.html
> +            <button type="submit" name="send" id="btm-send">Send</button>
```suggestion
            <button name="send" id="btm-send">Send</button>
```

2020-05-06 22:59 UTC, juancho11gm commented
The PR still containing the `3-semantic-html/basic.html` here.

2020-05-09 14:34 UTC, pushdev-code approved these changes

2020-05-09 14:37 UTC, merged